### ISSUE TITLE
Hexatomic crashes on MacOS

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#409] opened 2022-10-10 10:01 UTC
**Describe the bug**

As [reported in the JOSS review](https://github.com/openjournals/joss-reviews/issues/4825#issuecomment-1272056131), Hexatomic crashes on MacOS.

This issue tracks that bug. @reckart, could you please complete the missing info in the sections below, so that we can reproduce and fix this? Many thanks 🙏!

**To reproduce the bug**

**Expected behavior**

- Hexatomic runs fine on MacOS.

**Screenshots**

![](https://user-images.githubusercontent.com/1410238/194635304-9e366fac-0c60-4b39-aab4-1fde1193e37f.png).

**Desktop (please complete the following information):**
 - Operating System: MacOS **[version?]**
 - Hexatomic Version: 1.0.1
 - Java Version: **[Version? Using the bundled JRE?]**
 

**Additional context**

**Comment by reckart** [comment] 2022-10-10 10:09
* Download hexatomic-1.0.1-macosx.cocoa.x86_64.zip
* Extract it
* Double-click on Hexatomic.app
* See error

**Comment by reckart** [comment] 2022-10-10 10:10
OS: macOS 12.6

Java: openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Zulu18.30+11-CA (build 18.0.1+10)
OpenJDK 64-Bit Server VM Zulu18.30+11-CA (build 18.0.1+10, mixed mode, sharing)

**Comment by reckart** [comment] 2022-10-10 10:15
If I start from the command line, I get a different behavior:

```
% ./hexatomic
12:13:10.749 [main] INFO  o.c.h.c.ApplicationLifecycle - Logging configured from logback.xml in the Hexatomic root folder
12:13:10.857 [main] INFO  o.c.h.f.Activator - Using /.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins as Pepper module resource folder
12:13:10.894 [main] INFO  o.c.h.f.Activator - Installing Pepper module from file:/.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins/exmaralda-emf-api-1.2.2.jar
12:13:11.003 [main] INFO  o.c.h.f.Activator - Installing Pepper module from file:/.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins/gson-2.8.7.jar
12:13:11.023 [main] INFO  o.c.h.f.Activator - Installing Pepper module from file:/.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins/pepperModules-EXMARaLDAModules-1.3.1.jar
12:13:11.088 [main] INFO  o.c.h.f.Activator - Installing Pepper module from file:/.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins/pepperModules-GraphAnnoModules-2.0.1.jar
12:13:11.117 [main] INFO  o.c.h.f.Activator - Installing Pepper module from file:/.../Downloads/hexatomic.app/Contents/Eclipse/configuration/org.eclipse.osgi/38/0/.cp/pepper-plugins/pepperModules-PAULAModules-1.3.0.jar
12:13:12.069 [Worker-0: Update Job] INFO  o.c.h.c.u.UpdateRunner - Provisioning session created
```

<img width="571" alt="Screenshot 2022-10-10 at 12 14 29" src="https://user-images.githubusercontent.com/1410238/194843984-fabdbeaa-617e-41df-82ab-4ceb1ad32e4e.png">

The app window then also appears.

Closing the app and trying with a double-click on Hexatomic.app again brings up the error from before about `.metadata` being read-only.

**Comment by sdruskat** [comment] 2022-10-10 10:24
Thanks very much for these info, @reckart! We'll get this fixed as soon as possible.

@thomaskrause, can you get your hands on a MacOS 12.6 (VM?) to test this behaviour?

**Comment by thomaskrause** [comment] 2022-10-11 08:40
@reckart Did you extract the ZIP file to the `Applications` folder or to some other location? The error message about the `.metadata` file being read-only was caused by some newer MacOS sandbox mechanism.

In the [installation instructions](https://hexatomic.github.io/hexatomic/user/v1.0/installation.html), we had to add specific instructions for MacOS because of this sandbox and other, older security mechanisms. Can you check if the problem persists when you move the downloaded ZIP-file to the `Applications` folder? Manual unzipping should not be necessary.

We might want to extend the release notes to mention the different installation process on MacOS more prominently. I also find some of the wording in the instructions needs some clarification to not further confuse users. Like "For Mac OS X, we provide an .app file called hexatomic.app.", when the user never sees the ".app" extensions when following the instructions, but only the installed Icon and application name.

**Comment by reckart** [comment] 2022-10-11 08:43
If I move the application from the "Downloads" folder to the "Applications" folder, it starts up. I still get the "Couldn't find ProvisioningJob" dialog though.

TBH, I don't tend to read documentation before installing stuff. I just went to the [downloads page,](https://github.com/hexatomic/hexatomic/releases/tag/v1.0.1), downloaded the MacOS zip, extracted it and ran it.

**Comment by reckart** [comment] 2022-10-11 08:49
If you could provide the OS X version as a DMG with one of these nice "Please drag XXX to the Application folder" display, I think it would be a better user experience for OS X users.

**Comment by thomaskrause** [comment] 2022-10-11 09:01
> If I move the application from the "Downloads" folder to the "Applications" folder, it starts up. I still get the "Couldn't find ProvisioningJob" dialog though.
> 
> TBH, I don't tend to read documentation before installing stuff. I just went to the [downloads page,](https://github.com/hexatomic/hexatomic/releases/tag/v1.0.1), downloaded the MacOS zip, extracted it and ran it.

Yes, that's totally understandable since the downloaded format (what am I downloading and how as I typically handle this kind of files) should be self-explaining. That's why when there is any deviation from the default way of doing things we should make it very clear at the location of the download (like the release notes), that something is different.

Also, we should definitely look into providing Hexatomic as DMG instead of a ZIP file. @sdruskat We should make a separate issue about that.

Thanks also for the report of the "Did you start Hexatomic out of the Eclipse IDE message". I get it to on MacOS after the first start where I had to confirm that I still trust the authors, too. This might be some sandbox-effect from a blocked network connection or an internal bug in the logic.  But the error message is not helpful in any way and too obstructive. I added an issue for that #410

**Comment by reckart** [comment] 2022-10-11 09:05
I get this on every start:

<img width="590" alt="Screenshot 2022-10-11 at 11 04 44" src="https://user-images.githubusercontent.com/1410238/195047560-ccb0f671-1e52-4373-9af6-851b1741b966.png">

**Comment by thomaskrause** [comment] 2022-11-25 10:58
I added the DMG feature as a new issue #427

As far as I understand, with the fixes about the update notification and the installation by moving the application to the `Applications` folder (and documenting this more clearly) this issue is resolved. Please re-open if you disagree.

**Closed by thomaskrause** 2022-11-25 10:58 UTC
Labels: bug, 📃 JOSS-paper-2022
