### ISSUE TITLE
Ctrl-key selection in graph viewer is erratic

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#131] opened 2020-02-06 15:00 UTC
**Describe the bug**

Selecting additional segments while pressing the control key sometimes doesn't work, only on the second click. This seems independent of timing, as waiting between clicks doesn't change behaviour.

Sometimes, the layout changes on the *first* click as well, while the selected additional segment isn't selected.

You can see this in the following screen recording (open in new tab so you can see everything). The first instance shows non-selection on first click, the second instance (cut together from a longer recording) shows a slight change in layout on the first click (`structure1 goes up a level) as well as non-selection. Selection always on the second click. Note that Ctrl has been pressed during all operations.

I've also seen selection on the third click only, although I couldn't reproduce this.

This is also seems independent of #132.

**To reproduce the bug**
1. Open the Salt example project
2. Open the graph editor on the first document
3. Deselect pointing relations
4. Select spans
5. Select second segment
6. Press and hold `Ctrl`
7. Click on the third segment -> no selection, but sometimes a layout change
8. Click on third segment again -> selection

**Expected behavior**

The selection in the filter list is made on the first click.

**Screenshots**

![ctrl-error-hxtmc](https://user-images.githubusercontent.com/3007126/73948318-1daaa280-48f9-11ea-99f0-d06d7c828795.gif)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Hexatomic Version: #124 
 - Java Version: OpenJDK 8

**Comment by thomaskrause** [comment] 2020-02-19 16:28
I can't reproduce this with the latest `develop` branch. Following the instructions, the selection is always applied on first click. Probably, some code was throwing an error silently and aborted the redraw. This might have been fixed by the overhaul of the segmentation computation in #124  Please-reopen if this is still an issue on your system.

**Comment by thomaskrause** [comment] 2020-02-19 16:31
Ok, for future me:
To trigger this it is best to click on the same element in rapid repition.

**Comment by thomaskrause** [comment] 2020-02-19 16:36
Since clicking fast is necessary, we should check if the click is detected as double click an therefore causes this behaviour. Or maybe a previous rendering is still in progress and blocks the selection. If I wait a little bit before I click the last segment again (like 1 second seems to be enough on my computer), the selection works as intended.

**Comment by sdruskat** [comment] 2020-02-21 11:32
OMM, even with waiting >1 sec. you have to click on the second segment twice to make it work (`develop` state of now).

Open GIF in new window, mouse clicks recorded, Ctrl-key pressed before and held during selecting second segment.

![voko](https://user-images.githubusercontent.com/3007126/75031235-12817600-54a6-11ea-9c00-88ae55d4882f.gif)

**Closed** 2020-05-11 10:47 UTC
Labels: bug
