### ISSUE TITLE
No merging in grid view?

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#423] opened 2022-10-30 11:20 UTC
**Describe the bug**
I don't see the option for merging cells in the grid view when selecting two adjacent cells and right-clicking.

**To reproduce the bug**
1. Import text
2. Open grid view
3. Add new column
4. select two cells in the new column
5. right-click

**Expected behavior**
According to the documentation, there should be an option to merge cells.

**Screenshots**
![Screenshot 2022-10-30 at 12 20 09](https://user-images.githubusercontent.com/1410238/198875804-c6b27944-0650-4869-b862-c48498b29047.png)

**Desktop (please complete the following information):**
 - Operating System: OS X 12.6
 - Hexatomic Version: 1.0.1
 - Java Version: Java 18

**Comment by sdruskat** [comment] 2022-11-28 22:12
Hi @reckart, thanks for opening this issue, and sorry for the late reply.

The [user documentation notes in the section on merging spans](https://hexatomic.github.io/hexatomic/user/v1.0/usage/grid-editor/editing-values.html#merging-spans), that

> You can merge spans that are in the same annotation column and **have the same annotation value**: ...

This is why your selection across two _different_ annotation values does not display the option to merge spans.

In this basic implementation of merging spans, no option to pick one/more/all of many annotation values across selected spans is given. We may implement this if users request it.

Closing this now, but please feel free to continue the discussion, or re-open if you don't agree that this is not a bug.

**Closed by sdruskat** 2022-11-28 22:12 UTC
Labels: bug
