### ISSUE TITLE
Trying to save document edited and saved across 2 editors throws InvocationTargetException

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#214] opened 2020-08-18 20:37 UTC
**Describe the bug**

When editing and saving one and the same document across two editors, you may run into an `InvocationTargetException` when saving.

**To reproduce the bug**
1. Open example corpus
2. Open doc1 with graph editor (editor1)
3. Do `t test`
4. Save
5. Open doc1 in a second graph editor (editor2)
6. Do `t test2`
7. Save
8. (Re-)Activate editor1
9. Do `t test3`
10. Save
11. See error

**Expected behavior**

I would expect that in neither combination of editing and saving of one document from more than one editor would throw an exception on saving.

**Screenshots**

![Peek 2020-08-18 22-29](https://user-images.githubusercontent.com/3007126/90562622-cd16da80-e1a2-11ea-8c34-0c0771937a4d.gif)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Hexatomic Version: 0.4.2
 - Java Version: AdoptOpenJDK 11
 

**Additional context**

- Doesn't seem to be a timing issue. Waiting for a few secs between each action doesn't change the outcome.
- Doesn't seem to be an issue with the Grid Editor... Doing the same and changing annotation values doesn't produce the error.
- Perhaps this has to do with tokenization?

**Comment by thomaskrause** [comment] 2020-09-12 14:06
I can't reproduce this in my machine but from the behavior you describe, this looks like it could be caused by the same code that was fixed in 2b3a56b35e9133d1f2adbe82cb19b3986c0992fa.

The graph editor controller has a reference to both the document graph and the currently selected textual data source. When the document is saved, the document graph is updated, but not the selected textual data source. This causes a mix up to where the tokens are added to.

**Comment by thomaskrause** [comment] 2020-09-16 08:33
Fixed in release 0.4.4 #221

**Closed by thomaskrause** 2020-09-16 08:33 UTC
Labels: bug
