### ISSUE TITLE
IndexOutOfBoundsException in graph viewer when pointing relations are selected

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#132] opened 2020-02-06 15:25 UTC
**Describe the bug**

Depending on the selection of segments, sometimes selecting more than one segment throws an IOOBE.

**To reproduce the bug**
1. Open the first document of the Salt example in the graph viewer
2. Include spans (the IOOBE should now be thrown)
3. Select the second segment
4. Additionally select the third segment -> IOOBE is thrown

Cf. gif below, which also shows examples of #131 (watch for dual clicks).

Stack trace:

````
!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-02-06 17:58:53.972
!MESSAGE Internal Error
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at org.eclipse.draw2d.geometry.PointList.getPoint(PointList.java:194)
	at org.eclipse.draw2d.MidpointLocator.getReferencePoint(MidpointLocator.java:64)
	at org.eclipse.draw2d.AbstractLocator.relocate(AbstractLocator.java:111)
	at org.eclipse.draw2d.DelegatingLayout.layout(DelegatingLayout.java:75)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1096)
	at org.eclipse.draw2d.PolylineConnection.layout(PolylineConnection.java:179)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1899)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.FreeformViewport$FreeformViewportLayout.calculatePreferredSize(FreeformViewport.java:25)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.draw2d.ScrollPaneSolver.solve(ScrollPaneSolver.java:82)
	at org.eclipse.draw2d.FigureCanvas.layoutViewport(FigureCanvas.java:325)
	at org.eclipse.draw2d.FigureCanvas.access$4(FigureCanvas.java:323)
	at org.eclipse.draw2d.FigureCanvas$3.notifyValidating(FigureCanvas.java:292)
	at org.eclipse.draw2d.UpdateManager.fireValidating(UpdateManager.java:143)
	at org.eclipse.draw2d.DeferredUpdateManager.performValidation(DeferredUpdateManager.java:217)
	at org.eclipse.draw2d.DeferredUpdateManager.performUpdate(DeferredUpdateManager.java:193)
	at org.eclipse.zest.core.viewers.internal.AbstractStructuredGraphViewer.internalRefresh(AbstractStructuredGraphViewer.java:339)
	at org.eclipse.jface.viewers.StructuredViewer.internalRefresh(StructuredViewer.java:1250)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$3(StructuredViewer.java:1477)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1393)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1354)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1477)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1438)
	at org.eclipse.jface.viewers.StructuredViewer.setFilters(StructuredViewer.java:1570)
	at org.corpus_tools.hexatomic.graph.GraphEditor.updateView(GraphEditor.java:405)
	at org.corpus_tools.hexatomic.graph.GraphEditor.access$0(GraphEditor.java:363)
	at org.corpus_tools.hexatomic.graph.GraphEditor$UpdateViewListener.widgetSelected(GraphEditor.java:697)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

````

**Expected behavior**

Selecting more than one segment should not throw an exception, or, the exception message should point to issues in the model, if there are any (and if this causes the exception).

**Screenshots**

![ioobe](https://user-images.githubusercontent.com/3007126/73950711-ad058500-48fc-11ea-81c1-e67fbf940169.gif)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Hexatomic Version: #124 
 - Java Version: OpenJDK 8

**Comment by thomaskrause** [comment] 2020-02-19 16:13
Duplicate of #145 and will be fixed in #150 . The root cause is, that whenever an edge is a straight line, there is a wrong assumption about the number of points the edge has.

**Closed by thomaskrause** 2020-02-19 16:13 UTC
Labels: bug
